# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quit_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import main_window #import Ui_MainWindow
class Ui_QuitWindow(object):
    def openplaywindow(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=main_window.Ui_MainWindow()
        self.ui.setupUi(self.window)
        QuitWindow.hide()
        self.window.show()
    def quitwindow(self):
        self.close()
    #    QCoreApplication.instance().quit() 
       # QuitWindow.hide()
    



    def setupUi(self, QuitWindow):
        QuitWindow.setObjectName("QuitWindow")
        QuitWindow.resize(453, 478)
        self.centralwidget = QtWidgets.QWidget(QuitWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(130, 190, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 270, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        QuitWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QuitWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 21))
        self.menubar.setObjectName("menubar")
        QuitWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QuitWindow)
        self.statusbar.setObjectName("statusbar")
        QuitWindow.setStatusBar(self.statusbar)

        self.retranslateUi(QuitWindow)
        QtCore.QMetaObject.connectSlotsByName(QuitWindow)
        self.pushButton1.clicked.connect(self.openplaywindow)
        self.pushButton_2.clicked.connect(self.quitwindow)

    def retranslateUi(self, QuitWindow):
        _translate = QtCore.QCoreApplication.translate
        QuitWindow.setWindowTitle(_translate("QuitWindow", "MainWindow"))
        self.pushButton1.setText(_translate("QuitWindow", "Replay Game"))
        self.pushButton_2.setText(_translate("QuitWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QuitWindow = QtWidgets.QMainWindow()
    ui = Ui_QuitWindow()
    ui.setupUi(QuitWindow)
    QuitWindow.show()
    sys.exit(app.exec_())
